#if !canImport(ObjectiveC)
import XCTest

extension AdjacencyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AdjacencyTests = [
        ("testAdjacencyWithNoEdges", testAdjacencyWithNoEdges),
        ("testDirectedEdgeAdjacency", testDirectedEdgeAdjacency),
        ("testDirectedLoopAdjacency", testDirectedLoopAdjacency),
        ("testUndirectedEdgeAdjacency", testUndirectedEdgeAdjacency),
        ("testUndirectedEdgeAdjacencyWithRepeatedVertices", testUndirectedEdgeAdjacencyWithRepeatedVertices),
        ("testUndirectedLoopAdjacency", testUndirectedLoopAdjacency),
    ]
}

extension ArrayMutateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArrayMutateTests = [
        ("testMutate", testMutate),
        ("testNestedMutate", testNestedMutate),
    ]
}

extension ConstructorsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConstructorsTests = [
        ("testCompleteGraphConstructor", testCompleteGraphConstructor),
        ("testEmptyCompleteGraphConstructor", testEmptyCompleteGraphConstructor),
        ("testSingletonCompleteGraphConstructor", testSingletonCompleteGraphConstructor),
        ("testSingletonStarGraphConstructor", testSingletonStarGraphConstructor),
        ("testStarGraphConstructor", testStarGraphConstructor),
    ]
}

extension CycleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CycleTests = [
        ("testDetectCyclesEdges1", testDetectCyclesEdges1),
        ("testDetectCyclesVertices1", testDetectCyclesVertices1),
        ("testFullyConnectedEdges", testFullyConnectedEdges),
        ("testFullyConnectedVertices", testFullyConnectedVertices),
    ]
}

extension DijkstraGraphTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DijkstraGraphTests = [
        ("testDijkstra1", testDijkstra1),
        ("testDijkstra2", testDijkstra2),
        ("testDijkstra3", testDijkstra3),
        ("testRemovalWithDijkstra", testRemovalWithDijkstra),
    ]
}

extension EdgeRemovalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EdgeRemovalTests = [
        ("testRemoveAllEdges", testRemoveAllEdges),
        ("testRemoveDirectedEdge", testRemoveDirectedEdge),
    ]
}

extension EdgeRepresentationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EdgeRepresentationTests = [
        ("testDirectedAndUndirectedEdgeRepresentation", testDirectedAndUndirectedEdgeRepresentation),
        ("testDirectedAndUndirectedLoopsRepresentation", testDirectedAndUndirectedLoopsRepresentation),
        ("testDirectedEdgeRepresentation", testDirectedEdgeRepresentation),
        ("testDirectedLoopRepresentation", testDirectedLoopRepresentation),
        ("testRepresentationAfterRemoveDirectedEdge", testRepresentationAfterRemoveDirectedEdge),
        ("testRepresentationAfterRemoveDuplicatedDirectedEdge", testRepresentationAfterRemoveDuplicatedDirectedEdge),
        ("testRepresentationAfterRemoveDuplicatedUndirectedEdge", testRepresentationAfterRemoveDuplicatedUndirectedEdge),
        ("testRepresentationAfterRemoveUndirectedEdge", testRepresentationAfterRemoveUndirectedEdge),
        ("testTwoDirectedEdgesRepresentation", testTwoDirectedEdgesRepresentation),
        ("testTwoDirectedLoopsRepresentation", testTwoDirectedLoopsRepresentation),
        ("testTwoUndirectedEdgesRepresentation", testTwoUndirectedEdgesRepresentation),
        ("testTwoUndirectedLoopsRepresentation", testTwoUndirectedLoopsRepresentation),
        ("testUndirectedEdgeRepresentation", testUndirectedEdgeRepresentation),
        ("testUndirectedLoopRepresentation", testUndirectedLoopRepresentation),
    ]
}

extension EdgeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EdgeTests = [
        ("testDirectedEdgeJoins", testDirectedEdgeJoins),
        ("testUndirectedEdgeJoins", testUndirectedEdgeJoins),
        ("testUnweightedEdgeEquality", testUnweightedEdgeEquality),
        ("testWeightedEdgeEquality", testWeightedEdgeEquality),
    ]
}

extension MSTTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MSTTests = [
        ("testMST1", testMST1),
        ("testMST2", testMST2),
    ]
}

extension SwiftGraphCodableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftGraphCodableTests = [
        ("testComplexWeightedEncodableDecodable", testComplexWeightedEncodableDecodable),
        ("testEncodableDecodable", testEncodableDecodable),
    ]
}

extension SwiftGraphSearchTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftGraphSearchTests = [
        ("testBFS1", testBFS1),
        ("testBFS2", testBFS2),
        ("testBFS3", testBFS3),
        ("testBFS4", testBFS4),
        ("testBFS5", testBFS5),
        ("testBFS6", testBFS6),
        ("testBfsGoalTestOnInitialVertex", testBfsGoalTestOnInitialVertex),
        ("testBfsInCompleteGraphWithGoalTestByIndex", testBfsInCompleteGraphWithGoalTestByIndex),
        ("testBFSNotFound", testBFSNotFound),
        ("testBfsVisitOrderWithCycle", testBfsVisitOrderWithCycle),
        ("testBFSWithCycle", testBFSWithCycle),
        ("testDFS1", testDFS1),
        ("testDFS2", testDFS2),
        ("testDFS3", testDFS3),
        ("testDFS4", testDFS4),
        ("testDFS5", testDFS5),
        ("testDFS6", testDFS6),
        ("testDfsDoesntVisitTwice", testDfsDoesntVisitTwice),
        ("testDfsGoalTestOnInitialVertex", testDfsGoalTestOnInitialVertex),
        ("testDfsInCompleteGraphWithGoalTestByIndex", testDfsInCompleteGraphWithGoalTestByIndex),
        ("testDFSNotFound", testDFSNotFound),
        ("testDfsVisitOrderWithCycle", testDfsVisitOrderWithCycle),
        ("testDFSWithCycle", testDFSWithCycle),
        ("testFindAllBfs", testFindAllBfs),
        ("testFindAllDfs", testFindAllDfs),
        ("testTraverseBfsOnCycle", testTraverseBfsOnCycle),
        ("testTraverseDfsOnCycle", testTraverseDfsOnCycle),
    ]
}

extension SwiftGraphSortTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftGraphSortTests = [
        ("testDAG", testDAG),
        ("testTopologicalSort", testTopologicalSort),
    ]
}

extension SwiftGraphTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftGraphTests = [
        ("testSequenceTypeAndCollectionType", testSequenceTypeAndCollectionType),
        ("testSubscript", testSubscript),
    ]
}

extension UnionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnionTests = [
        ("testAssociativity", testAssociativity),
        ("testCommutativity", testCommutativity),
        ("testDisjointUnion", testDisjointUnion),
        ("testEmptyGraph", testEmptyGraph),
        ("testIdentityEmptyGraph", testIdentityEmptyGraph),
        ("testImmutabilityOfInputGraphs", testImmutabilityOfInputGraphs),
        ("testMultipleParameters", testMultipleParameters),
        ("testUnionFirstInCommon", testUnionFirstInCommon),
        ("testUnionLastInCommon", testUnionLastInCommon),
        ("testUnionWithSelf", testUnionWithSelf),
    ]
}

extension UniqueElementsGraphContainerEdgeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UniqueElementsGraphContainerEdgeTests = [
        ("testExample", testExample),
        ("testPerformanceExample", testPerformanceExample),
    ]
}

extension UnweightedGraphTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnweightedGraphTests = [
        ("testCycleInitializerDirected", testCycleInitializerDirected),
        ("testCycleInitializerUndirected", testCycleInitializerUndirected),
        ("testPathInitializerDirected", testPathInitializerDirected),
        ("testPathInitializerUndirected", testPathInitializerUndirected),
        ("testRepeatedEdges", testRepeatedEdges),
    ]
}

extension UnweightedUniqueElementsGraphHashableInitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnweightedUniqueElementsGraphHashableInitTests = [
        ("testCycleInitializerDirected", testCycleInitializerDirected),
        ("testCycleInitializerUndirected", testCycleInitializerUndirected),
        ("testPathInitializerDirected", testPathInitializerDirected),
        ("testPathInitializerUndirected", testPathInitializerUndirected),
    ]
}

extension UnweightedUniqueElementsGraphHashableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnweightedUniqueElementsGraphHashableTests = [
        ("testUniqueDirectedEdges", testUniqueDirectedEdges),
        ("testUniqueDirectedLoop", testUniqueDirectedLoop),
        ("testUniqueDirectedLoop2", testUniqueDirectedLoop2),
        ("testUniqueEdgesCombined1", testUniqueEdgesCombined1),
        ("testUniqueEdgesCombined2", testUniqueEdgesCombined2),
        ("testUniqueEdgesCombined3", testUniqueEdgesCombined3),
        ("testUniqueEdgesCombined4", testUniqueEdgesCombined4),
        ("testUniqueUndirectedEdges", testUniqueUndirectedEdges),
        ("testUniqueUndirectedEdges2", testUniqueUndirectedEdges2),
        ("testUniqueUndirectedLoop", testUniqueUndirectedLoop),
        ("testUniqueUndirectedLoop2", testUniqueUndirectedLoop2),
        ("testUniqueVertexAfterAddition", testUniqueVertexAfterAddition),
        ("testUniqueVertexAfterInit", testUniqueVertexAfterInit),
    ]
}

extension UnweightedUniqueElementsGraphInitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnweightedUniqueElementsGraphInitTests = [
        ("testCycleInitializerDirected", testCycleInitializerDirected),
        ("testCycleInitializerUndirected", testCycleInitializerUndirected),
        ("testPathInitializerDirected", testPathInitializerDirected),
        ("testPathInitializerUndirected", testPathInitializerUndirected),
    ]
}

extension UnweightedUniqueElementsGraphTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnweightedUniqueElementsGraphTests = [
        ("testUniqueDirectedEdges", testUniqueDirectedEdges),
        ("testUniqueDirectedLoop", testUniqueDirectedLoop),
        ("testUniqueDirectedLoop2", testUniqueDirectedLoop2),
        ("testUniqueEdgesCombined", testUniqueEdgesCombined),
        ("testUniqueUndirectedEdges", testUniqueUndirectedEdges),
        ("testUniqueUndirectedEdges2", testUniqueUndirectedEdges2),
        ("testUniqueUndirectedLoop", testUniqueUndirectedLoop),
        ("testUniqueUndirectedLoop2", testUniqueUndirectedLoop2),
        ("testUniqueVertexAfterAddition", testUniqueVertexAfterAddition),
        ("testUniqueVertexAfterInit", testUniqueVertexAfterInit),
    ]
}

extension VertexRemovalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VertexRemovalTests = [
        ("testCitesInverseAfterRemove", testCitesInverseAfterRemove),
        ("testCountsAfterRemoval", testCountsAfterRemoval),
        ("testFirstVertexRemoval", testFirstVertexRemoval),
    ]
}

extension WeightedGraphTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WeightedGraphTests = [
        ("testEdgeExistsDirected", testEdgeExistsDirected),
        ("testEdgeExistsUndirected", testEdgeExistsUndirected),
        ("testWeightsDirected", testWeightsDirected),
        ("testWeightsMixed", testWeightsMixed),
        ("testWeightsUndirected", testWeightsUndirected),
    ]
}

extension WeightedUniqueElementsGraphTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WeightedUniqueElementsGraphTests = [
        ("testUniqueDirectedEdgesDifferentWeight", testUniqueDirectedEdgesDifferentWeight),
        ("testUniqueDirectedEdgesSameWeight", testUniqueDirectedEdgesSameWeight),
        ("testUniqueDirectedLoop2DifferentWeight", testUniqueDirectedLoop2DifferentWeight),
        ("testUniqueDirectedLoop2SameWeight", testUniqueDirectedLoop2SameWeight),
        ("testUniqueDirectedLoopDifferentWeight", testUniqueDirectedLoopDifferentWeight),
        ("testUniqueDirectedLoopSameWeight", testUniqueDirectedLoopSameWeight),
        ("testUniqueEdgesCombinedDifferentWeight1", testUniqueEdgesCombinedDifferentWeight1),
        ("testUniqueEdgesCombinedDifferentWeight2", testUniqueEdgesCombinedDifferentWeight2),
        ("testUniqueEdgesCombinedSameWeight", testUniqueEdgesCombinedSameWeight),
        ("testUniqueUndirectedEdges2", testUniqueUndirectedEdges2),
        ("testUniqueUndirectedEdgesDifferentWeight", testUniqueUndirectedEdgesDifferentWeight),
        ("testUniqueUndirectedEdgesSameWeight", testUniqueUndirectedEdgesSameWeight),
        ("testUniqueUndirectedLoop2DifferentWeight", testUniqueUndirectedLoop2DifferentWeight),
        ("testUniqueUndirectedLoop2SameWeight", testUniqueUndirectedLoop2SameWeight),
        ("testUniqueUndirectedLoopDifferentWeight", testUniqueUndirectedLoopDifferentWeight),
        ("testUniqueUndirectedLoopSameWeight", testUniqueUndirectedLoopSameWeight),
        ("testUniqueVertexAfterAddition", testUniqueVertexAfterAddition),
        ("testUniqueVertexAfterInit", testUniqueVertexAfterInit),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AdjacencyTests.__allTests__AdjacencyTests),
        testCase(ArrayMutateTests.__allTests__ArrayMutateTests),
        testCase(ConstructorsTests.__allTests__ConstructorsTests),
        testCase(CycleTests.__allTests__CycleTests),
        testCase(DijkstraGraphTests.__allTests__DijkstraGraphTests),
        testCase(EdgeRemovalTests.__allTests__EdgeRemovalTests),
        testCase(EdgeRepresentationTests.__allTests__EdgeRepresentationTests),
        testCase(EdgeTests.__allTests__EdgeTests),
        testCase(MSTTests.__allTests__MSTTests),
        testCase(SwiftGraphCodableTests.__allTests__SwiftGraphCodableTests),
        testCase(SwiftGraphSearchTests.__allTests__SwiftGraphSearchTests),
        testCase(SwiftGraphSortTests.__allTests__SwiftGraphSortTests),
        testCase(SwiftGraphTests.__allTests__SwiftGraphTests),
        testCase(UnionTests.__allTests__UnionTests),
        testCase(UniqueElementsGraphContainerEdgeTests.__allTests__UniqueElementsGraphContainerEdgeTests),
        testCase(UnweightedGraphTests.__allTests__UnweightedGraphTests),
        testCase(UnweightedUniqueElementsGraphHashableInitTests.__allTests__UnweightedUniqueElementsGraphHashableInitTests),
        testCase(UnweightedUniqueElementsGraphHashableTests.__allTests__UnweightedUniqueElementsGraphHashableTests),
        testCase(UnweightedUniqueElementsGraphInitTests.__allTests__UnweightedUniqueElementsGraphInitTests),
        testCase(UnweightedUniqueElementsGraphTests.__allTests__UnweightedUniqueElementsGraphTests),
        testCase(VertexRemovalTests.__allTests__VertexRemovalTests),
        testCase(WeightedGraphTests.__allTests__WeightedGraphTests),
        testCase(WeightedUniqueElementsGraphTests.__allTests__WeightedUniqueElementsGraphTests),
    ]
}
#endif
